### ISSUE TITLE
[메인페이지] 여행지목록

### ISSUE THREAD

**Issue by baymaxxxxx** [codestates/TMT-client#11]
### ISSUE

- Group: `client`
- Type: `feature`
- Detail:

### TODO

- [x]  여행지 목록 CSS
- [ ]  response로 들어온 data를 랜더하기
- [ ]  해당 여행지를 선택했을 때 post요청(insertSpot)

### Labels

- Estimated time: `E: 1h`
- Group : `client`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`, `Middle`, `Low`
